# Generated by Django 6.0.3 on 2026-04-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('extracted_text', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('mode', models.CharField(default='ocr', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
